language: ruby
rvm:
- 2.4.0
env:
  matrix:
  - DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
- bundle exec rspec
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: PzGlAU9iVBhz3FauGBFc5JCYr8KUT4dMFFxwOcBuEpQ82ErCt6e4LQvxPNoDyZyrPpLj9qdB0Xlj4zNfO8TnAb1XznTETn+YjGOXCf419/WQfeXEj6Gb971QmxUUd+BNmQhml2RQ9/JWjL+fLt46aVci4YDBFSHotFPtMtxBpfg3eEKuQ0+Q83PFbUM7No5kTdAJyd1Tp/lroq+mp7qOw7Og/9G+sO7KMWrSEv+Pem3UMld6V9aWfghqwahKWhHszZ/tPPaNVMTJYu1DDPSwbp4egKmzsdvPSJiYQnPAWq2hg5cyQkHvGjIbu08N9Fm80yxa6uYjGTG0PO+2habrKkl4ZYlmn3Ok5JrVUqDqOk2DcSqFyU0pDA6BUWJ7sox+0RbnONt/jBkzvpvceF6LSciJbc8ymPVEp2pFfOQtAFlRYXXV4ap9aOWqvosAi7N6YfbADdVqcS4Yg4igi59OpCZNreeBDu21qHU8KBOsipt15aOz8fEAEE816S8vs8GyvJl0n5efNvBfv2Sx8WNMo6cqs8/0R/1o16zWiez20S79NYsCNIHFgWeyaIWVVPqUG19pauOTXnBW/5gCAUpspxfF/5X4qEpGJoI2sjLrbjQvEVzFFpBAvwfwW2Jjqf5n/zMdKBc74QjXSitfU25LM+VGLEarclLHVbJPYPCcMgc=
  app: pokertournament
  on:
    repo: notmarkmiranda/seven
